### ISSUE TITLE
_dirnav_child does not work together with enhancd

### ISSUE THREAD

**Issue by timomeh** [gparker42/zsh-dirnav#1]
`_dirnav_child` didn't work for me. I always got "no such file or directory". I narrowed it down to this line: 

https://github.com/gparker42/zsh-dirnav/blob/009446cdfb13a7552cdf0d68c5ceb6fa4ce7c585/dirnav#L75

I'm also using https://github.com/b4b4r07/enhancd, which doesn't support the `cd -- $dir` syntax. `_dirnav_child` does work without enhancd.

To be honest, I don't know the difference between `cd $dir` and `cd -- $dir`. It would work for me without the `--`.

**Comment by gparker42** [comment]
In zsh builtin functions, `--` terminates option processing. This matters for `cd` if the directory name happens to look like a valid option to `cd`. For example, if `$dir == "-1"` then `cd $dir` expands to `cd -1` and will change to the first directory on the dirstack, even if there is actually a directory named `-1` here; but `cd -- $dir` will always change to the directory named `-1`.

enhancd appears to have added support for `--` recently (https://github.com/b4b4r07/enhancd/commit/e562a195313e9d7ad01ebdfebdd412e76f716acd). Is your copy up-to-date?

I thought that `autoload -U` would ignore shell aliases inside dirnav's implementation. I guess that doesn't do what I thought. It might be better for dirnav to use `builtin cd` instead of bare `cd`.

**Comment by timomeh** [comment]
Wow, thanks for the great explanation! TIL

I've updated enhancd, but it still doesn't behave correctly. Now enhancd prepends the current working directory (e.g. it tries to cd into `/Users/timo/abc/Users/timo/abc/def`).

I solved it by simply loading enhancd after dirnav. I thought the order wouldn't matter – however, I could've tried that earlier. 😅 It works great now.

`builtin cd` sounds like a good approach to make it _just work_ ✨
